### ISSUE TITLE
Add type support to nuxt.config.ts 

### ISSUE THREAD

**Issue by moltar** [wemake-services/wemake-vue-template#1347]
`nuxt.config.ts` can be typed.

```ts
import { Configuration } from '@nuxt/types'

const config: Configuration = {
  // ...
}

export default config
```

**Comment by sobolevn** [comment]
@moltar are you interested in working on this? I would appreciate a PR! 

P.S. Not sure if you are aware of https://hacktoberfest.digitalocean.com/
