### ISSUE TITLE
ERROR StylelintWebpackPlugin cannot be invoked without 'new'

### ISSUE THREAD

**Issue by tiagobar** [wemake-services/wemake-vue-template#1356]
I am getting this error when "npm run dev" is executed by docker-compose in a clean install. I didn't test it in local environment.

I got stylelint-webpack-plugin back to 0.10.5 version and it works fine.

**Comment by sobolevn** [comment]
I guess, that it might be related: https://github.com/wemake-services/wemake-vue-template/pull/1354

Can you please try to downgrade it?

**Comment by tiagobar** [comment]
> I guess, that it might be related: #1354
> 
> Can you please try to downgrade it?

Indeed it's related to #1335 

My downgrade tests:
1.0.2 -> fail
1.0.1 -> fail (same error)
0.10.5 -> Works fine

**Comment by sobolevn** [comment]
Can you please send a pr with the fix?

**Comment by tiagobar** [comment]
> Can you please send a pr with the fix?

PR done!
