### ISSUE TITLE
ESLint doesn't work on WebStorm IDE

### ISSUE THREAD

**Issue by alza54** [wemake-services/wemake-vue-template#1378]
Hello, I tried to use this template on WebStorm IDE, but ESLint was not working. 
I noticed that _parser_ option in @vue/typescript package (https://github.com/vuejs/eslint-config-typescript/blob/master/index.js#L8) was causing the issue. 
I replaced _@vue/typescript_ in .eslintrc file with _@nuxtjs/eslint-config-typescript_ and it works like a charm. 

I think _@vue/typescript_ shouldn't be used anymore, because it has last commit 9 months ago compared to _@nuxtjs/eslint-config-typescript_ which has last commit 1 month ago. _@nuxtjs/eslint-config-typescript_ is also suggested by official Nuxt.js documentation (https://typescript.nuxtjs.org/guide/lint.html). Nuxt.js config defines rule 'no-unused-vars' so there might be a need to overwrite it with `'@typescript-eslint/no-unused-vars': ['error', { args: 'none' }]` in .eslintrc file. By the way on line 12 in .eslintrc file (https://github.com/wemake-services/wemake-vue-template/blob/master/template/.eslintrc.js#L12) there is 'plugin:@typescript-eslint/recommended' which is already extended by _@wemake-services/typescript_
also thanks for the template, it's very awesome :)

**Comment by sobolevn** [comment]
Oh, wow! Thanks a lot for such a detailed description. Do you want to submit a fix?

It would be an awesome help for me at the moment 👍

**Comment by alza54** [comment]
Sure, I'll try tomorrow

**Comment by alza54** [comment]
#1383

**Comment by alza54** [comment]
#1383
