### ISSUE TITLE
 Docker Broken: Fatal Error: Cannot find module 'vue/package.json'

### ISSUE THREAD

**Issue by madStitcher** [wemake-services/wemake-vue-template#1519]
After completing these install steps 

1. git clone https://github.com/wemake-services/wemake-vue-template.git
1. npx vue-cli init ./wemake-vue-template my_test_app
1. Installed nvm
1. nvm install
1. nvm use
1. npm install
1. Copied and modified environment file
1. docker-compose up

This is when the error "FATAL  Cannot find module 'vue/package.json'" shows up. 

Right after...
vue_1  | ℹ Listening on: http://172.19.0.2:3000/
vue_1  | ℹ Preparing project for development
vue_1  | ℹ Initial build may take a while

**Comment by sobolevn** [comment]
Thanks, I will fix it today

**Comment by madStitcher** [comment]
FYI:  I get the same error when trying to run this outside of docker...

1. cd wemake-vue-template
1. git pull
1. cd ../
1. npx vue-cli init ./wemake-vue-template test4
1. cd test4
1. nvm install
1. nvm use
1. npm install
1. npm run dev

And I'm getting the same error...

`
ℹ Preparing project for development                                                                                                                                                               12:31:21
ℹ Initial build may take a while                                                                                                                                                                  12:31:21

 FATAL  Cannot find module 'vue/package.json'                                                                                                                                                     12:31:21

  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
  at Function.Module._load (internal/modules/cjs/loader.js:562:25)
  at Module.require (internal/modules/cjs/loader.js:690:17)
  at require (internal/modules/cjs/helpers.js:25:18)
  at Resolver.requireModule (node_modules/@nuxt/core/dist/core.js:571:26)
  at Builder.validateTemplate (node_modules/@nuxt/builder/dist/builder.js:5638:38)
  at Builder.build (node_modules/@nuxt/builder/dist/builder.js:5566:12)
`

**Comment by madStitcher** [comment]
Just to give you more info on this error.

**Comment by madStitcher** [comment]
Ugh, I didn't mean to close this. Sorry.

**Comment by lishanda** [comment]
I have the same issue, it seems that `npm install` doesn't install peer dependencies.
`npm ls` lists all missing deps at the end:

> npm ERR! peer dep missing: eslint@^3 || ^4 || ^5, required by eslint-plugin-vue-a11y@0.0.31
npm ERR! peer dep missing: vue@2.x, required by @vue/test-utils@1.0.0-beta.30
npm ERR! peer dep missing: vue@^2.x, required by vue-jest@3.0.5
npm ERR! peer dep missing: vue@^2.5.17, required by vue-typedi@1.1.1
npm ERR! peer dep missing: vue@^2.5.0, required by vuex-class@0.3.2
npm ERR! peer dep missing: vue@^2.5.17, required by vuex-simple@2.2.0
npm ERR! peer dep missing: vue-template-compiler@^2.x, required by @vue/test-utils@1.0.0-beta.30
npm ERR! peer dep missing: vue-template-compiler@^2.x, required by vue-jest@3.0.5      
npm ERR! peer dep missing: newtype-ts@^0.2.1, required by io-ts-types@0.4.7
npm ERR! peer dep missing: vue-class-component@^6.3.2, required by vue-typedi@1.1.1    
npm ERR! peer dep missing: stylelint@^9.8.0, required by stylelint-use-nesting@1.2.1   
npm ERR! peer dep missing: eslint@^5.0.0, required by eslint-plugin-vue@5.2.3
npm ERR! peer dep missing: eslint@^5.0.0, required by vue-eslint-parser@5.0.0
npm ERR! peer dep missing: vue@^2.5.0, required by vuex-class@0.3.2
npm ERR! peer dep missing: vue@^2.5.0, required by vuex-class@0.3.2
npm ERR! peer dep missing: vue-router@^3.0.0, required by vuex-router-sync@5.0.0 

I suppose that [latest build](https://travis-ci.com/wemake-services/wemake-vue-template/builds/143178639) fails for the same reason, as testing launches

(starting from line 630)
> npm run test:engine && npm run test:unit && npm run lint
> wemake_vue_demo@0.0.0 test:engine /code
> check-engine
Checking versions... 
✔ node was validated with 10.16.
✔ npm was validated with >=6.
 Environment looks good!
> wemake_vue_demo@0.0.0 test:unit /code
> cross-env NODE_ENV=test jest
 RUNS  ...
 FAIL  tests/components/comment.spec.ts
 RUNS  ...
● Test suite failed to run
    **Cannot find module 'vue-template-compiler' from 'vue-test-utils.js'**
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (node_modules/@vue/test-utils/dist/vue-test-utils.js:5:27)

**Comment by sobolevn** [comment]
Related https://github.com/vuejs/vue-test-utils/issues/1399
