### ISSUE TITLE
Eslint validates node_modules, throws errors

### ISSUE THREAD

**Issue by Tobjoern** [wemake-services/wemake-vue-template#1695]
I have some trouble using the '@minogin/vue-drag-resize-rotate' with the template.
After installing it, eslint throws various errors (and checks the module for errors), claiming the module is not installed, which is not the case. I am not an eslint expert, it could very well be that there is a bug with eslint, but I don't know.

I used the latest versions of all modules.

Reproduction:
https://github.com/Tobjoern/wemake-import-issue

Thanks for your help.

**Comment by sobolevn** [comment]
Hm, that is strange. What happens if you try to remove `@minogin/vue-drag-resize-rotate`?

**Comment by Tobjoern** [comment]
It works fine then, but I have noticed similar issues with other packages. I will send further information shortly.

**Comment by Tobjoern** [comment]
I have a similiar issue with the 'vue-credit-card-field' package. I added a reproduction under the 'test2' page.

**Comment by sobolevn** [comment]
Can you please try to disable all these lines one by one and tell which one causes this fail? https://github.com/wemake-services/wemake-vue-template/blob/master/template/.eslintrc.js#L7-L16

**Comment by Tobjoern** [comment]
Even after commenting out all these lines, the error still persists.

I also commented out https://github.com/wemake-services/wemake-vue-template/blob/master/template/nuxt.config.ts#L123-L128, as an attempt to completely dissable eslint. [This](https://nuxtjs.org/guide/development-tools/#eslint-and-prettie) explains how eslint is supposed to be implemented in nuxt.js. However, even after commenting this implementation out, eslint is still active. From my current understanding this means some third party (plugin) runs eslint. But this third party doesn't seem to be properly setup, as th .eslintingore file is (ironically) ignored.

**Comment by sobolevn** [comment]
@Tobjoern I have copied your repo and tried to reproduce: 

```
~/Desktop/wemake-import-issue  master ✔                                              
» npm run lint:js

> your_vue_project@0.0.0 lint:js /Users/sobolev/Desktop/wemake-import-issue
> eslint --cache --ext .js,.ts,.vue,.json --ignore-path .gitignore .

```

I don't have any issues.

**Comment by Tobjoern** [comment]
I'm sorry, I didn't explain properly.
I re-added wemake-services' default eslint configuration, and now npm run lint:js works fine.
However npm run dev throws a bunch of errors, even though eslint (and stylelint) are completely disabled the way it is described in [the nuxt.js documentation](https://nuxtjs.org/guide/development-tools/#eslint-and-prettie).

**Comment by sobolevn** [comment]
Oh, I see. Here's the issue you are talking about:
<img width="752" alt="Снимок экрана 2020-04-01 в 12 28 46" src="https://user-images.githubusercontent.com/4660275/78121702-60c65500-7414-11ea-92d5-4479184c2daa.png">

**Comment by sobolevn** [comment]
It looks like that this is not `eslint`. But it is `typescript` error.

**Comment by Tobjoern** [comment]
Hm okay, and how can one resolve this issue?

**Comment by sobolevn** [comment]
There are two ways AFAIK:
1. The wrong one: `--skipLibCheck` from https://www.typescriptlang.org/docs/handbook/compiler-options.html
2. The correct one: sending a PR with the fix to `@minogin/vue-drag-resize-rotate`

Feel free to post your solution!

**Comment by Tobjoern** [comment]
Thanks for the soluition, I thought it was eslint!
I decided to go with the 'skipLibCheck' option.
In tsconfig.json: compilerOptions.skipLibCheck: true
