### ISSUE TITLE
consider separating states into their own files

### ISSUE THREAD

**Issue by eli007s** [wemake-services/wemake-vue-template#1726]
would having the modules states in their own files be possible.

like `actions.ts` `mutations.ts` and `getters.ts`?

**Comment by sobolevn** [comment]
It can be possible, you can do something like: 

```
@Module()
public commentsActions = new CommentsActionsModule()

@Module()
public commentsGetters = new CommentsGettersModule()
```

here: https://github.com/wemake-services/wemake-vue-template/blob/master/template/client/logic/store.ts#L15

But, I don't recommend to do so. It is better to keep your modules small. So every getter / action / mutation will fit inside perfectly.
