### ISSUE TITLE
Fresh installation fails

### ISSUE THREAD

**Issue by straybro** [wemake-services/wemake-vue-template#1902]
```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal
```
```
yarn -v
1.22.4
```

`npx vue-cli init ./wemake-vue-template your_vue_project`

Then I removed 'checkengine' from package.json. But with node v13 it is the same.
```
node -v
v10.19.0     
```                                                                      

```
cd your_vue_project
yarn install
yarn run dev
```

> yarn run v1.22.4                                                                                    
> $ cross-env NODE_ENV=development nuxt-ts                                                            
>                                                                                                    
>                                                                                                     
>    ╭────────────────────────────────────────╮                                                       
>    │                                        │                                                       
>    │   Nuxt.js @ v2.13.3                    │                                                                                                                                                               
>    │                                        │                                                       
>    │   ▸ Environment: development           │     
>    │   ▸ Rendering:   server-side           │     
>    │   ▸ Target:      server                │     
>    │                                        │     
>    │   Listening: http://localhost:3000/   │     
>    │                                        │     
>    ╰────────────────────────────────────────╯     
> 
> ℹ Preparing project for development                                                     21:03:18    
> ℹ Initial build may take a while                                                        21:03:18    
> ✔ Builder initialized                                                                   21:03:18    
> ✔ Nuxt files generated    

> ℹ Preparing project for development                                                     21:03:18
> ℹ Initial build may take a while                                                        21:03:18
> ✔ Builder initialized                                                                   21:03:18
> ✔ Nuxt files generated                                                                  21:03:18
> 
> ● Client █████████████████████████ building (26%) 139/165 modules 26 active
>  node_modules/core-js/modules/_iobject.js
> 
> ✖ Server
>   Compiled with some errors in 18.55s
> 
> ℹ Starting type checking service...                                     nuxt:typescript 21:03:26
> 
> ✖ Client
>   Compiled with some errors in 15.69s
> 
> ✖ Server
>   Compiled with some errors in 18.55s
> 
> ℹ Type checking in progress...                                          nuxt:typescript 21:03:42
> 
>  ERROR  Failed to compile with 1 errors                                 friendly-errors 21:03:42
> 
> This relative module was not found:                                     friendly-errors 21:03:42
>                                                                         friendly-errors 21:03:42
> *** ../client/store/index.ts in ./.nuxt/store.js**                          friendly-errors 21:03:42
> ℹ Waiting for file changes                                                              21:03:42
> ℹ Memory usage: 340 MB (RSS: 450 MB)                                                    21:03:42
> ℹ Listening on: http://localhost:3000/                                                 21:03:42
> ℹ No type errors found                                                  nuxt:typescript 21:03:53
> ℹ Version: typescript 3.9.6                                             nuxt:typescript 21:03:53
> ℹ Time: 26493 ms                                                        nuxt:typescript 21:03:53

 **It says that ../client/store/index.ts not found in ./.nuxt/store.js. But it is there.** It's very strange.

.nuxt/store.js
```
import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

let store = {};

(function updateModules () {
  store = normalizeRoot(require('../client/store/index.ts'), 'store/index.ts')

  // If store is an exported method = classic mode (deprecated)

  if (typeof store === 'function') {
    return console.warn('Classic mode for store/ is deprecated and will be removed in Nuxt 3.')
  }

  // Enforce store modules
  store.modules = store.modules || {}

  // If the environment supports hot reloading...

  if (process.client && module.hot) {
    // Whenever any Vuex module is updated...
    module.hot.accept([
      '../client/store/index.ts',
    ], () => {
      // Update `root.modules` with the latest definitions.
      updateModules()
      // Trigger a hot update in the store.
      window.$nuxt.$store.hotUpdate(store)
    })
  }
})()

// createStore
export const createStore = store instanceof Function ? store : () => {
  return new Vuex.Store(Object.assign({
    strict: (process.env.NODE_ENV !== 'production')
  }, store))
}

function normalizeRoot (moduleData, filePath) {
  moduleData = moduleData.default || moduleData

  if (moduleData.commit) {
    throw new Error(`[nuxt] ${filePath} should export a method that returns a Vuex instance.`)
  }

  if (typeof moduleData !== 'function') {
    // Avoid TypeError: setting a property that has only a getter when overwriting top level keys
    moduleData = Object.assign({}, moduleData)
  }
  return normalizeModule(moduleData, filePath)
}

function normalizeModule (moduleData, filePath) {
  if (moduleData.state && typeof moduleData.state !== 'function') {
    console.warn(`'state' should be a method that returns an object in ${filePath}`)

    const state = Object.assign({}, moduleData.state)
    // Avoid TypeError: setting a property that has only a getter when overwriting top level keys
    moduleData = Object.assign({}, moduleData, { state: () => state })
  }
  return moduleData
}
```

**Comment by sobolevn** [comment]
How's your use-case is different from the one in our CI? https://github.com/wemake-services/wemake-vue-template/actions?query=workflow%3ABuild

I might be able to reproduce it then.

**Comment by straybro** [comment]
yarn install, yarn lint and yarn test work fine with the same warnings as in CI, but build fails.
```
  115:12  warning  Argument 'config' should be typed        @typescript-eslint/explicit-module-boundary-types
  115:20  warning  Object pattern argument should be typed  @typescript-eslint/explicit-module-boundary-types
```
I found that issue exists because ts-loader is not present in dependencies. I have added it to packages.json and now it works!

**Comment by sobolevn** [comment]
@straybro PR is welcome! 👍
