### ISSUE TITLE
Why design the 'client/logic' directory

### ISSUE THREAD

**Issue by ErrorJe** [wemake-services/wemake-vue-template#2143]
i want to know this design thought, tks

**Comment by sobolevn** [comment]
Sorry, I don't really understand your question 🙂 

Can you please be more specific?

**Comment by ErrorJe** [comment]
> Sorry, I don't really understand your question 🙂
> 
> Can you please be more specific?

emm... for example, we often create a types directory for TypeScript type declaration files. However, I see the directory called logic in your project and don't quite understand what functional files this is save for

**Comment by sobolevn** [comment]
I use `logic/` in almost all of my projects. That's where I put pure-functions, use-cases and business scenarios, validation, etc.

Basically I treat other folders as infrastructure, and `logic` as, well, business logic 🙂 

Example: https://github.com/wemake-services/wemake-python-styleguide/tree/master/wemake_python_styleguide/logic
