### ISSUE TITLE
Server is running at http://undefined:undefined

### ISSUE THREAD

**Issue by franktopel** [wemake-services/wemake-vue-template#221]
Following your default instructions, trying to run the dev server using `yarn dev` gives me this:

`Server is running at http://undefined:undefined`

Then I tried `yarn build` followed by `yarn start` which results in

```
@connexo > yarn start
yarn run v1.3.2
$ cross-env NODE_ENV=production node server
server started at http://undefined:undefined
```

In both cases I tried `http://localhost:8080` but no success. Which port is your default port?

**Comment by sobolevn** [comment]
Sorry, that probably a documentation issue.
Could you please try to copy `config/.env.template` to `config/.env`?

In this file all settings are specified. By default we are using:
```
DEV_HOST=localhost
DEV_PORT=4000
```

Related: https://github.com/wemake-services/wemake-vue-template/issues/209
A PR is more than welcomed!

**Comment by franktopel** [comment]
Thanks for helping me solve the issue. I created a PR and added a "Running the project" section to the readme.md.
