### ISSUE TITLE
Switch to classic Store mode

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-vue-template#487]
https://nuxtjs.org/guide/vuex-store#classic-mode
It is the same as #485 

Some users report that it is hard for them to understand how new `store` folder works.
They already have different files layout and logics separation.

So, switching to the `classic` mode will allow us to help these users to switch to our template without loosing anything.

Leaving `nuxt`'s dark magic aside.

**Comment by kirillvy** [comment]
I'll do this one

**Comment by sobolevn** [comment]
Closed via https://github.com/wemake-services/wemake-vue-template/pull/491
