### ISSUE TITLE
Consider adding real e2e tests

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-vue-template#504]
This looks promising: https://gitlab.com/cypress-io/cypress-example-docker-gitlab

Working example: https://github.com/chrisvfritz/vue-enterprise-boilerplate/tree/master/tests/e2e
Docs: https://github.com/chrisvfritz/vue-enterprise-boilerplate/blob/master/docs/tests.md#end-to-end-tests-with-cypress

**Comment by sobolevn** [comment]
Limitations that really bothers me:
- https://github.com/cypress-io/cypress/issues/310

**Comment by sobolevn** [comment]
One more example: https://github.com/chymz/nuxt-template/tree/master/template/cypress

**Comment by sobolevn** [comment]
Ok, here's my thoughts about this problem:

| Framework  | Engine                               | Assertions |                                                   Different browsers                                                   |   Speed  | Docker                                                                         | Linting                                                                                           |
|------------|--------------------------------------|------------|:----------------------------------------------------------------------------------------------------------------------:|:--------:|--------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------|
| Cypress    | Tests are injected into the web page | Custom     |                                [Some](https://github.com/cypress-io/cypress/issues/1096)                               | Bearable | [Slim](https://github.com/cypress-io/cypress/issues/419)                       | [Custom eslint config](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/index.js)  |
| JSDom      | Native server-side JS                | Any        |                                                           No                                                           | Best     | Any, including Alpine                                                          | Not needed                                                                                        |
| Nightwatch | Selenium/WebDriver                   | Custom     |                     [Yes](https://github.com/nightwatchjs/nightwatch/wiki/Internet-Explorer-Setup)                     | Slow     | Container Hell                                                                 | Not available                                                                                     |
| Puppeteer  | Headless Chrome                      | Any        |                                                           No                                                           | Bearable | [Alpine](https://github.com/GoogleChrome/puppeteer/issues/379)                 | Not available                                                                                     |
| TestCafe   | Tests are injected into the web page | Custom     | [Yes](http://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browsers/browser-support.html) | Bearable | [Alpine](https://github.com/DevExpress/testcafe/blob/master/docker/Dockerfile) | [Custom eslint config](https://github.com/miherlosev/eslint-plugin-testcafe/blob/master/index.js) |

Features:
<img width="712" alt="2018-05-20 18 17 57" src="https://user-images.githubusercontent.com/4660275/40280338-303b914e-5c5a-11e8-89ed-bb3fbb8c3d69.png">


## Resources

Resources used in this research:
- https://medium.com/welldone-software/an-overview-of-javascript-testing-in-2018-f68950900bc3
- https://quizlet.com/blog/cypress-the-future-of-end-to-end-testing-for-web-applications
- https://medium.com/@adrian_lewis/top-5-most-rated-node-js-frameworks-for-end-to-end-web-testing-f8ebca4e5d44
- https://medium.com/tech-quizlet/cypress-the-future-of-end-to-end-testing-for-web-applications-8ee108c5b255

## Showcase

Cypress: https://github.com/chrisvfritz/vue-enterprise-boilerplate/tree/master/tests/e2e
TestCafe: https://github.com/egoist/vuepack/blob/master/template/test/e2e/index.js
Puppeteer: https://github.com/studbits/nuxt-jest-puppeteer

**Comment by sobolevn** [comment]
## TestCafe

Sample:
```
import { Selector } from 'testcafe'; // first import testcafe selectors

fixture `Getting Started`// declare the fixture
    .page `https://devexpress.github.io/testcafe/example`;  // specify the start page


//then create a test and place your code there
test('My first test', async t => {
    await t
        .typeText('#developer-name', 'John Smith')
        .click('#submit-button')

        // Use the assertion to check if the actual header text is equal to the expected one
        .expect(Selector('#article-header').innerText).eql('Thank you, John Smith!');
});

```


Result:
```
» npx testcafe chrome testcafe.js 
npx: installed 285 in 21.6s
 Running tests in:
 - Chrome 63.0.3239 / Mac OS X 10.11.6

 Getting Started
 ✓ My first test


 1 passed (3s)

```

**Comment by sobolevn** [comment]
## TestCafe + Nuxt

Sample:

```js
import VueSelector from 'testcafe-nuxt-selectors'

fixture('Getting Started')
  .page('http://localhost:3000')
  .beforeEach(async () => await VueSelector())

test('My first test', async (t) => {
  const root = VueSelector()
  const rootVue = await root.getVue()

  await t.expect(root.exists).ok()
  await t.expect(rootVue.state.layoutName).eql('default')
})
```

Output:

```
» ./node_modules/.bin/testcafe chrome  --app "yarn dev" --app-init-delay 10000 testcafe.js
 Running tests in:
 - Chrome 63.0.3239 / Mac OS X 10.11.6

 Getting Started
 ✓ My first test


 1 passed (2s)
```

**Comment by christian-bromann** [comment]
@sobolevn why not consider [webdriver.io](http://webdriver.io)?

**Comment by sobolevn** [comment]
@christian-bromann thanks for advice! I did not know that this product exists. 

I try to remove `selenium` from our toolchain. The main reason for is speed and setup complexity.
We run everything inside `docker-compose` for development and testing. And I need a simple solution to just work in this setup. When we had `nightwatch` with `webdriver` bindings it was really hard to manage all the test containers with `jvm` and stuff.

Speed. I need to be able to run all tests before merging a PR. So, it should not take long to start and execute tests. My previous experience with `selenium` was too slow.

Can you please correct me if I am wrong about these two point? Thanks!

**Comment by christian-bromann** [comment]
You can definitely get a decent speed when setting up the driver properly. By running Chrome headless with Chromedriver (instead of the Selenium standalone server) your test should be quick. A quick google search gave me this project which seems to exactly do that: https://github.com/kaitoy/webdriverio-chrome

**Comment by kartojal** [comment]
Just to contribute with my grain of sand, you can run Testcafe with concurrency enabled, with chrome and/or firefox in headless mode. For example you can divide 100 tests into 2 concurrent headless chrome browsers, doing each instance 50 tests. In that way it improves the testing speed. Ex:
`testcafe chrome:headless -c 2 test/e2e/*spec*`

**Comment by sobolevn** [comment]
@kartojal thanks! Currently testing it out.
