### ISSUE TITLE
Fix flow and jsx

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-vue-template#683]
We can not upgrade `flow` due to the bug with `@jsx`.

Actual error:

```
/code/client/components/ActionBar.vue
  34:8   error  Cannot create `div` element because a callable signature is missing in statics of `ActionBar` (see line 19)     flowtype-errors/show-errors
  35:10  error  Cannot create `button` element because a callable signature is missing in statics of `ActionBar` (see line 19)  flowtype-errors/show-errors
```

Related:
https://github.com/wemake-services/wemake-vue-template/pull/679
https://travis-ci.org/wemake-services/wemake-vue-template/builds/406968425?utm_source=github_status&utm_medium=notification

**Comment by sobolevn** [comment]
This should help: https://github.com/facebook/flow/blob/e0933585af5cc856fab674adb3ffdbfb353f89ab/newtests/jsx_pragma/test.js

**Comment by ArmorDarks** [comment]
Thanks for the hint, though it still sounds like a hack...

Note that your `jsx` function probably should be at least something like this, otherwise Flow will throw:

```js
function jsx (element: string, props: ?Object, children: (string | Object)): Object { return {} }
```
