### ISSUE TITLE
Add docs

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-vue-template#9]

**Comment by sobolevn** [comment]
https://github.com/documentationjs/documentation

**Comment by sobolevn** [comment]
https://github.com/vuejs/gitbook-plugin-theme-vuejs

**Comment by rlabrecque** [comment]
I'd recommend adding yarn, docker, (and jdk?) to the requirements second of the readme.

**Comment by rlabrecque** [comment]
The biggest thing that I got hung up on when first starting to use this was that it never explained that I had to create `config/.env`

**Comment by sobolevn** [comment]
@rlabrecque do you have any suggestions on doc tools?

**Comment by rlabrecque** [comment]
I've used jekyll and hugo in the past but they were honestly pretty overkill, Starting with a github wiki might be the quickest way to get started. If you want to move it elsewhere it's easy enough. Writing is the hard part regardless of tools :)
