### ISSUE TITLE
can I break something? > node 10.14.2 and yarn 1.12.3

### ISSUE THREAD

**Issue by stkac** [wemake-services/wemake-vue-template#904]
Hi, can I break something if change node and yarn version?
I see the package.json and have:

```
  "engines": {
    "node": "10.8",
    "yarn": "1.9"
```
and my system have:

```
yarn install v1.12.3
[1/5] Validating package.json...
error app@0.1.0: The engine "node" is incompatible with this module. Expected version "10.8". Got "10.14.2"
error app@0.1.0: The engine "yarn" is incompatible with this module. Expected version "1.9". Got "1.12.3"
```
### Always up-to-date with the help of @dependabot
> that it's true?

Thanks in advance,

**Comment by sobolevn** [comment]
@stkac I am pretty sure that you won't brake anything. 
I am just too busy to merge these PRs from `@dependabot`: https://github.com/wemake-services/wemake-vue-template/pulls

You can send a PR with the updated requirements. It will be very helpful.
Anyways, thanks for your question. Feel free to report any problems you will find.

**Comment by sobolevn** [comment]
@stkac hey, check out our migration process to `typescript`! There are a lot of goodies. 
https://github.com/wemake-services/wemake-vue-template/pull/1038

Closing this issue.
